### ISSUE TITLE
No Airways for YSSY

### ISSUE THREAD

**Issue by GitWalnut** [OceanicRegion/XO-Sector-File#26]
there is no airways so i cant see routes.

**Comment by CWalton724364** [comment]
Airways are installed within the Melbourne sector, tested and working. 

Airways are not installed in the Brisbane sector. It would be heavy on performance to add airways for Brisbane as it also requires us to add fixes. All SID transition fixes are within the YMMM FIR therefore there shouldn't be a requirement to see Brisbane airways or fixes when controlling Sydney. We don't need fixes in Brisbane for STARs, as we can manage this using coordinates.
